language: go

go:
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - docker swarm init

script:
  - go test -tags=unit -v -count=1 ./...
  - go test -tags=integration -v -count=1 ./test/
