language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

services:
  - docker

before_install:
  - docker swarm init

script:
  - go test -tags=unit -v ./...
  - go test -tags=integration -v ./...